# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35336bec9ca25ce322a255110442140994de9277528460c82c8d9de6c48f15b9d2e0cfc37a54184564ea5510437089b3f3dd7c0063542917fbe282c8788c061c

test:
  secret_key_base: 982c95fc0382f7d6b71d7e6afa79d964511c1cd1436328a884d199694deb38beed5b1be0ff2e0ac9af5a2124409311fe54b286f5337d8276eab7cb4e541799b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
